### ISSUE TITLE
rundir in config.json

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/ExPyRe#31]
I had a problem with remote DFT calculation which has stopped with unreproducible error. 
I suspect this might have to do with read/write bottleneck. I'm supposed to carry out DFT calculation in scratch folder. 
I wanted to specify `rundir` in `config.json` file to scratch folder which is not the same as `.expyre`. 
But it seems like stage files for DFT submission is still generated in `.expyre` not what I have specified as `rundir` in `config.json`. 
Following is snippet of my `config.json` file. 
I wonder if I'm wrong with something or is it a bug.
I'll be appreciated for any comments. 

Best regards,
Hyunwook 

```
{
    "systems": {
        "local": {
            "host": null,
            "remsh_cmd": "/usr/bin/ssh",
            "scheduler": "slurm",
            "header": [
                "#SBATCH --no-requeue",
                "#SBATCH --nodes={num_nodes}",
                "#SBATCH --ntasks-per-node={num_cores}",
				"#SBATCH --mem=180000"
            ],
            "commands": [
                "module purge",
                "module load anaconda/3/2021.05",
                "module load gcc/10 intel/19.1.2 impi/2019.8 mkl/2020.2 fftw-mpi/3.3.9",
                "source ${MKLROOT}/bin/mklvars.sh intel64",
                "conda activate /u/hjung/conda-envs/mace_env",
                "export QUIP_ARCH=linux_x86_64_gfortran_openmp",
                "export QUIPPY_INSTALL_OPTS=--user",
                "export WFL_AUTOPARA_NPOOL=40",
                "export OMP_NUM_THREADS=1",
                "export GAP_FIT_OMP_NUM_THREADS=40",
                "export ASE_ESPRESSO_COMMAND='srun /u/hjung/Softwares/QE/qe-7.0/bin/pw.x -in PREFIX.pwi > PREFIX.pwo'",
				"export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mpcdf/soft/SLE_12/packages/x86_64/intel_parallel_studio/2020.2/mkl/lib/intel64/",
                "export ESPRESSO_PSEUDO='/u/hjung/Softwares/QE/pseudopotentials'"
            ],
            "partitions": {
                "tiny" : { "num_cores" : 1, "max_time" : "24:00:00", "max_mem" : "12GB" },
                "medium" : { "num_cores" : 40, "max_time" : "24:00:00", "max_mem" : "24GB" }
                },
			"rundir": "/u/hjung/workflow/scratch"
        },

```

**Comment by bernstei** [comment]
I believe that a local stage directory is always created. It's copied (with rsync?) to the remote machine (into rundir), then the code is run there, and then the contents are copied back into the local stage directory.  Have you checked out what's in the remote machine's `rundir` after the job fails? The directory structure can get a bit complicated, but do something like `ls -R /u/hjung/workflow/scratch` and look at every file that might be a stderr/stdout-type of thing.

**Comment by jungsdao** [comment]
My `EXPYRE_ROOT` environment variable is defined in `.bashrc` like this: `export EXPYRE_ROOT=/u/hjung/.expyre`.
And still when I submit my DFT job, it's making stage file in `.expyre` not `rundir` which I have defined in `config.json`. 
This is the output of `ls -R` in `rundir` (`~/workflow/scratch`) which contains nothing.
```
(base) hjung@cobra01:~/workflow/scratch> ls -R
.:
```
Am I missing something?

**Comment by bernstei** [comment]
I have a tentative fix. I'll open a PR. @jungsdao Do you know how to install from a github branch, so you can test it?

**Comment by jungsdao** [comment]
Yes, I can test it, Thank you for the fix!

**Comment by bernstei** [comment]
OK, I'll create the PR as soon as I make sure that the pytests pass.

**Comment by bernstei** [comment]
Can you check the branch `host_null_use_rundir`?

**Comment by bernstei** [comment]
It is intended, because that's more similar to how it works when you run on a remote machine, but let me think about whether that can be skipped.

**Comment by bernstei** [comment]
OK, I have an idea that should make this cleaner. I'll leave the PR that makes it use the `rundir` setting even if `host` is `None`, because I don't think it hurts.  It'll still default to running in the stage dir if you don't specify `run_dir`.

However, I'm adding a way for you to set the _stage dir_ explicitly, so it doesn't have to be the `EXPYRE_ROOT` (or wherever it found a `.expyre` or `_expyre`).  What you'll want to do is not specify`rundir`, but specify `"local_stage_dir": "path_to_your_scratch"` instead. Note that this key is set at the top level of the `config.json` dict, alongside `systems` (not in the dict item for a specific system).  This way it'll stage to scratch, then run directly in the stage dir (which is in scratch).  I'll let you know when it's ready to test.

**Comment by jungsdao** [comment]
I've tried after updating the branch, but I've got following error. 
I replaced `rundir` to `local_stage_dir` in `~/.expyre/config.json`.

```
Traceback (most recent call last):
  File "/raven/u/hjung/4_Free_energy_sampling/2_Cu/y_test/run_ref_calc.py", line 5, in <module>
    import wfl.autoparallelize
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/__init__.py", line 1, in <module>
    from .base import autoparallelize, autoparallelize_docstring
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/base.py", line 11, in <module>
    from .remote import do_remotely
  File "/raven/u/hjung/Softwares/workflow1/wfl/autoparallelize/remote.py", line 12, in <module>
    from expyre import ExPyRe, ExPyReJobDiedError
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/expyre/__init__.py", line 1, in <module>
    from .config import systems
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/expyre/config.py", line 144, in <module>
    init(os.environ.get("EXPYRE_ROOT", "@"))
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/expyre/config.py", line 136, in init
    systems[_sys_name] = System(rundir_extra=_rundir_extra, **_sys_data)
TypeError: __init__() got an unexpected keyword argument 'local_stage_dir'
```

**Comment by bernstei** [comment]
As my instructions say, `"local_stage_dir"` isn't inside the `"systems"` key, but at the _top level_ of the dict in `config.json`:
```
{"systems": {...
      },
  "local_stage_dir": "/scratch/....."
}
```

**Comment by bernstei** [comment]
That looks like a small bug on my side.  Give me a minute to push another version.

**Comment by bernstei** [comment]
Try after pulling again

**Comment by jungsdao** [comment]
Now it seems like working as expected. Thank you!

**Comment by bernstei** [comment]
Great.  I make want to make a test that checks the last bug you noticed, but I'll merge once that's done.
